// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: urls.proto
#ifndef GRPC_urls_2eproto__INCLUDED
#define GRPC_urls_2eproto__INCLUDED

#include "urls.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace encurtador {

// Definição do serviço de encurtamento de URL
class EncurtadorURL final {
 public:
  static constexpr char const* service_full_name() {
    return "encurtador.EncurtadorURL";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Encurtar uma URL longa e receber uma curta
    virtual ::grpc::Status EncurtarURL(::grpc::ClientContext* context, const ::encurtador::RequisicaoEncurtar& request, ::encurtador::RespostaEncurtar* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::encurtador::RespostaEncurtar>> AsyncEncurtarURL(::grpc::ClientContext* context, const ::encurtador::RequisicaoEncurtar& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::encurtador::RespostaEncurtar>>(AsyncEncurtarURLRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::encurtador::RespostaEncurtar>> PrepareAsyncEncurtarURL(::grpc::ClientContext* context, const ::encurtador::RequisicaoEncurtar& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::encurtador::RespostaEncurtar>>(PrepareAsyncEncurtarURLRaw(context, request, cq));
    }
    // Obter a URL longa original a partir do código curto
    virtual ::grpc::Status ObterURLLonga(::grpc::ClientContext* context, const ::encurtador::RequisicaoObter& request, ::encurtador::RespostaObter* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::encurtador::RespostaObter>> AsyncObterURLLonga(::grpc::ClientContext* context, const ::encurtador::RequisicaoObter& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::encurtador::RespostaObter>>(AsyncObterURLLongaRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::encurtador::RespostaObter>> PrepareAsyncObterURLLonga(::grpc::ClientContext* context, const ::encurtador::RequisicaoObter& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::encurtador::RespostaObter>>(PrepareAsyncObterURLLongaRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // Encurtar uma URL longa e receber uma curta
      virtual void EncurtarURL(::grpc::ClientContext* context, const ::encurtador::RequisicaoEncurtar* request, ::encurtador::RespostaEncurtar* response, std::function<void(::grpc::Status)>) = 0;
      virtual void EncurtarURL(::grpc::ClientContext* context, const ::encurtador::RequisicaoEncurtar* request, ::encurtador::RespostaEncurtar* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Obter a URL longa original a partir do código curto
      virtual void ObterURLLonga(::grpc::ClientContext* context, const ::encurtador::RequisicaoObter* request, ::encurtador::RespostaObter* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ObterURLLonga(::grpc::ClientContext* context, const ::encurtador::RequisicaoObter* request, ::encurtador::RespostaObter* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::encurtador::RespostaEncurtar>* AsyncEncurtarURLRaw(::grpc::ClientContext* context, const ::encurtador::RequisicaoEncurtar& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::encurtador::RespostaEncurtar>* PrepareAsyncEncurtarURLRaw(::grpc::ClientContext* context, const ::encurtador::RequisicaoEncurtar& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::encurtador::RespostaObter>* AsyncObterURLLongaRaw(::grpc::ClientContext* context, const ::encurtador::RequisicaoObter& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::encurtador::RespostaObter>* PrepareAsyncObterURLLongaRaw(::grpc::ClientContext* context, const ::encurtador::RequisicaoObter& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status EncurtarURL(::grpc::ClientContext* context, const ::encurtador::RequisicaoEncurtar& request, ::encurtador::RespostaEncurtar* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::encurtador::RespostaEncurtar>> AsyncEncurtarURL(::grpc::ClientContext* context, const ::encurtador::RequisicaoEncurtar& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::encurtador::RespostaEncurtar>>(AsyncEncurtarURLRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::encurtador::RespostaEncurtar>> PrepareAsyncEncurtarURL(::grpc::ClientContext* context, const ::encurtador::RequisicaoEncurtar& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::encurtador::RespostaEncurtar>>(PrepareAsyncEncurtarURLRaw(context, request, cq));
    }
    ::grpc::Status ObterURLLonga(::grpc::ClientContext* context, const ::encurtador::RequisicaoObter& request, ::encurtador::RespostaObter* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::encurtador::RespostaObter>> AsyncObterURLLonga(::grpc::ClientContext* context, const ::encurtador::RequisicaoObter& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::encurtador::RespostaObter>>(AsyncObterURLLongaRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::encurtador::RespostaObter>> PrepareAsyncObterURLLonga(::grpc::ClientContext* context, const ::encurtador::RequisicaoObter& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::encurtador::RespostaObter>>(PrepareAsyncObterURLLongaRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void EncurtarURL(::grpc::ClientContext* context, const ::encurtador::RequisicaoEncurtar* request, ::encurtador::RespostaEncurtar* response, std::function<void(::grpc::Status)>) override;
      void EncurtarURL(::grpc::ClientContext* context, const ::encurtador::RequisicaoEncurtar* request, ::encurtador::RespostaEncurtar* response, ::grpc::ClientUnaryReactor* reactor) override;
      void ObterURLLonga(::grpc::ClientContext* context, const ::encurtador::RequisicaoObter* request, ::encurtador::RespostaObter* response, std::function<void(::grpc::Status)>) override;
      void ObterURLLonga(::grpc::ClientContext* context, const ::encurtador::RequisicaoObter* request, ::encurtador::RespostaObter* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::encurtador::RespostaEncurtar>* AsyncEncurtarURLRaw(::grpc::ClientContext* context, const ::encurtador::RequisicaoEncurtar& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::encurtador::RespostaEncurtar>* PrepareAsyncEncurtarURLRaw(::grpc::ClientContext* context, const ::encurtador::RequisicaoEncurtar& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::encurtador::RespostaObter>* AsyncObterURLLongaRaw(::grpc::ClientContext* context, const ::encurtador::RequisicaoObter& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::encurtador::RespostaObter>* PrepareAsyncObterURLLongaRaw(::grpc::ClientContext* context, const ::encurtador::RequisicaoObter& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_EncurtarURL_;
    const ::grpc::internal::RpcMethod rpcmethod_ObterURLLonga_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Encurtar uma URL longa e receber uma curta
    virtual ::grpc::Status EncurtarURL(::grpc::ServerContext* context, const ::encurtador::RequisicaoEncurtar* request, ::encurtador::RespostaEncurtar* response);
    // Obter a URL longa original a partir do código curto
    virtual ::grpc::Status ObterURLLonga(::grpc::ServerContext* context, const ::encurtador::RequisicaoObter* request, ::encurtador::RespostaObter* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_EncurtarURL : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_EncurtarURL() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_EncurtarURL() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status EncurtarURL(::grpc::ServerContext* /*context*/, const ::encurtador::RequisicaoEncurtar* /*request*/, ::encurtador::RespostaEncurtar* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestEncurtarURL(::grpc::ServerContext* context, ::encurtador::RequisicaoEncurtar* request, ::grpc::ServerAsyncResponseWriter< ::encurtador::RespostaEncurtar>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_ObterURLLonga : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ObterURLLonga() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_ObterURLLonga() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ObterURLLonga(::grpc::ServerContext* /*context*/, const ::encurtador::RequisicaoObter* /*request*/, ::encurtador::RespostaObter* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestObterURLLonga(::grpc::ServerContext* context, ::encurtador::RequisicaoObter* request, ::grpc::ServerAsyncResponseWriter< ::encurtador::RespostaObter>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_EncurtarURL<WithAsyncMethod_ObterURLLonga<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_EncurtarURL : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_EncurtarURL() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::encurtador::RequisicaoEncurtar, ::encurtador::RespostaEncurtar>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::encurtador::RequisicaoEncurtar* request, ::encurtador::RespostaEncurtar* response) { return this->EncurtarURL(context, request, response); }));}
    void SetMessageAllocatorFor_EncurtarURL(
        ::grpc::MessageAllocator< ::encurtador::RequisicaoEncurtar, ::encurtador::RespostaEncurtar>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::encurtador::RequisicaoEncurtar, ::encurtador::RespostaEncurtar>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_EncurtarURL() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status EncurtarURL(::grpc::ServerContext* /*context*/, const ::encurtador::RequisicaoEncurtar* /*request*/, ::encurtador::RespostaEncurtar* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* EncurtarURL(
      ::grpc::CallbackServerContext* /*context*/, const ::encurtador::RequisicaoEncurtar* /*request*/, ::encurtador::RespostaEncurtar* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_ObterURLLonga : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ObterURLLonga() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::encurtador::RequisicaoObter, ::encurtador::RespostaObter>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::encurtador::RequisicaoObter* request, ::encurtador::RespostaObter* response) { return this->ObterURLLonga(context, request, response); }));}
    void SetMessageAllocatorFor_ObterURLLonga(
        ::grpc::MessageAllocator< ::encurtador::RequisicaoObter, ::encurtador::RespostaObter>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::encurtador::RequisicaoObter, ::encurtador::RespostaObter>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ObterURLLonga() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ObterURLLonga(::grpc::ServerContext* /*context*/, const ::encurtador::RequisicaoObter* /*request*/, ::encurtador::RespostaObter* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ObterURLLonga(
      ::grpc::CallbackServerContext* /*context*/, const ::encurtador::RequisicaoObter* /*request*/, ::encurtador::RespostaObter* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_EncurtarURL<WithCallbackMethod_ObterURLLonga<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_EncurtarURL : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_EncurtarURL() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_EncurtarURL() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status EncurtarURL(::grpc::ServerContext* /*context*/, const ::encurtador::RequisicaoEncurtar* /*request*/, ::encurtador::RespostaEncurtar* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_ObterURLLonga : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ObterURLLonga() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_ObterURLLonga() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ObterURLLonga(::grpc::ServerContext* /*context*/, const ::encurtador::RequisicaoObter* /*request*/, ::encurtador::RespostaObter* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_EncurtarURL : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_EncurtarURL() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_EncurtarURL() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status EncurtarURL(::grpc::ServerContext* /*context*/, const ::encurtador::RequisicaoEncurtar* /*request*/, ::encurtador::RespostaEncurtar* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestEncurtarURL(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_ObterURLLonga : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ObterURLLonga() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_ObterURLLonga() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ObterURLLonga(::grpc::ServerContext* /*context*/, const ::encurtador::RequisicaoObter* /*request*/, ::encurtador::RespostaObter* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestObterURLLonga(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_EncurtarURL : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_EncurtarURL() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->EncurtarURL(context, request, response); }));
    }
    ~WithRawCallbackMethod_EncurtarURL() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status EncurtarURL(::grpc::ServerContext* /*context*/, const ::encurtador::RequisicaoEncurtar* /*request*/, ::encurtador::RespostaEncurtar* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* EncurtarURL(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ObterURLLonga : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ObterURLLonga() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ObterURLLonga(context, request, response); }));
    }
    ~WithRawCallbackMethod_ObterURLLonga() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ObterURLLonga(::grpc::ServerContext* /*context*/, const ::encurtador::RequisicaoObter* /*request*/, ::encurtador::RespostaObter* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ObterURLLonga(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_EncurtarURL : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_EncurtarURL() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::encurtador::RequisicaoEncurtar, ::encurtador::RespostaEncurtar>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::encurtador::RequisicaoEncurtar, ::encurtador::RespostaEncurtar>* streamer) {
                       return this->StreamedEncurtarURL(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_EncurtarURL() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status EncurtarURL(::grpc::ServerContext* /*context*/, const ::encurtador::RequisicaoEncurtar* /*request*/, ::encurtador::RespostaEncurtar* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedEncurtarURL(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::encurtador::RequisicaoEncurtar,::encurtador::RespostaEncurtar>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ObterURLLonga : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ObterURLLonga() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::encurtador::RequisicaoObter, ::encurtador::RespostaObter>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::encurtador::RequisicaoObter, ::encurtador::RespostaObter>* streamer) {
                       return this->StreamedObterURLLonga(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ObterURLLonga() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ObterURLLonga(::grpc::ServerContext* /*context*/, const ::encurtador::RequisicaoObter* /*request*/, ::encurtador::RespostaObter* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedObterURLLonga(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::encurtador::RequisicaoObter,::encurtador::RespostaObter>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_EncurtarURL<WithStreamedUnaryMethod_ObterURLLonga<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_EncurtarURL<WithStreamedUnaryMethod_ObterURLLonga<Service > > StreamedService;
};

}  // namespace encurtador


#endif  // GRPC_urls_2eproto__INCLUDED
