# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: urls.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'urls.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nurls.proto\x12\nencurtador\"\'\n\x12RequisicaoEncurtar\x12\x11\n\turl_longa\x18\x01 \x01(\t\"%\n\x10RespostaEncurtar\x12\x11\n\turl_curta\x18\x01 \x01(\t\"\'\n\x0fRequisicaoObter\x12\x14\n\x0c\x63odigo_curto\x18\x01 \x01(\t\"\"\n\rRespostaObter\x12\x11\n\turl_longa\x18\x01 \x01(\t2\xa5\x01\n\rEncurtadorURL\x12K\n\x0b\x45ncurtarURL\x12\x1e.encurtador.RequisicaoEncurtar\x1a\x1c.encurtador.RespostaEncurtar\x12G\n\rObterURLLonga\x12\x1b.encurtador.RequisicaoObter\x1a\x19.encurtador.RespostaObterb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'urls_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUISICAOENCURTAR']._serialized_start=26
  _globals['_REQUISICAOENCURTAR']._serialized_end=65
  _globals['_RESPOSTAENCURTAR']._serialized_start=67
  _globals['_RESPOSTAENCURTAR']._serialized_end=104
  _globals['_REQUISICAOOBTER']._serialized_start=106
  _globals['_REQUISICAOOBTER']._serialized_end=145
  _globals['_RESPOSTAOBTER']._serialized_start=147
  _globals['_RESPOSTAOBTER']._serialized_end=181
  _globals['_ENCURTADORURL']._serialized_start=184
  _globals['_ENCURTADORURL']._serialized_end=349
# @@protoc_insertion_point(module_scope)
