# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: notas.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'notas.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bnotas.proto\x12\x0egerencia_notas\"W\n\x04Nota\x12\n\n\x02ra\x18\x01 \x01(\t\x12\x16\n\x0e\x63od_disciplina\x18\x02 \x01(\t\x12\x0b\n\x03\x61no\x18\x03 \x01(\x05\x12\x10\n\x08semestre\x18\x04 \x01(\x05\x12\x0c\n\x04nota\x18\x05 \x01(\x02\"]\n\x14\x43onsultaNotaResponse\x12\x0f\n\x07sucesso\x18\x01 \x01(\x08\x12\"\n\x04nota\x18\x02 \x01(\x0b\x32\x14.gerencia_notas.Nota\x12\x10\n\x08msg_erro\x18\x03 \x01(\t\"<\n\x16\x41lunoDisciplinaRequest\x12\n\n\x02ra\x18\x01 \x01(\t\x12\x16\n\x0e\x63od_disciplina\x18\x02 \x01(\t\"f\n\x13\x41\x64icionaNotaRequest\x12\n\n\x02ra\x18\x01 \x01(\t\x12\x16\n\x0e\x63od_disciplina\x18\x02 \x01(\t\x12\x0b\n\x03\x61no\x18\x03 \x01(\x05\x12\x10\n\x08semestre\x18\x04 \x01(\x05\x12\x0c\n\x04nota\x18\x05 \x01(\x02\".\n\x0eStatusResponse\x12\x0f\n\x07sucesso\x18\x01 \x01(\x08\x12\x0b\n\x03msg\x18\x02 \x01(\t\"\x1a\n\x0c\x41lunoRequest\x12\n\n\x02ra\x18\x01 \x01(\t\"A\n\rMediaResponse\x12\x0f\n\x07sucesso\x18\x01 \x01(\x08\x12\r\n\x05media\x18\x02 \x01(\x02\x12\x10\n\x08msg_erro\x18\x03 \x01(\t2\xbd\x03\n\x10GerenciadorNotas\x12V\n\rAdicionarNota\x12#.gerencia_notas.AdicionaNotaRequest\x1a\x1e.gerencia_notas.StatusResponse\"\x00\x12T\n\x0b\x41lterarNota\x12#.gerencia_notas.AdicionaNotaRequest\x1a\x1e.gerencia_notas.StatusResponse\"\x00\x12_\n\rConsultarNota\x12&.gerencia_notas.AlunoDisciplinaRequest\x1a$.gerencia_notas.ConsultaNotaResponse\"\x00\x12N\n\rCalcularMedia\x12\x1c.gerencia_notas.AlunoRequest\x1a\x1d.gerencia_notas.MediaResponse\"\x00\x12J\n\x10ListarNotasAluno\x12\x1c.gerencia_notas.AlunoRequest\x1a\x14.gerencia_notas.Nota\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'notas_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NOTA']._serialized_start=31
  _globals['_NOTA']._serialized_end=118
  _globals['_CONSULTANOTARESPONSE']._serialized_start=120
  _globals['_CONSULTANOTARESPONSE']._serialized_end=213
  _globals['_ALUNODISCIPLINAREQUEST']._serialized_start=215
  _globals['_ALUNODISCIPLINAREQUEST']._serialized_end=275
  _globals['_ADICIONANOTAREQUEST']._serialized_start=277
  _globals['_ADICIONANOTAREQUEST']._serialized_end=379
  _globals['_STATUSRESPONSE']._serialized_start=381
  _globals['_STATUSRESPONSE']._serialized_end=427
  _globals['_ALUNOREQUEST']._serialized_start=429
  _globals['_ALUNOREQUEST']._serialized_end=455
  _globals['_MEDIARESPONSE']._serialized_start=457
  _globals['_MEDIARESPONSE']._serialized_end=522
  _globals['_GERENCIADORNOTAS']._serialized_start=525
  _globals['_GERENCIADORNOTAS']._serialized_end=970
# @@protoc_insertion_point(module_scope)
